### ISSUE TITLE
Can you provide the pre-trained model ?

### ISSUE THREAD

**Issue by riviera1020** [franroldans/tfm-franroldan-wav2pix#4]
Interesting work and I want to infer using my own speech. Can you provide pre-trained model? Thank you.

**Comment by franroldans** [comment]
Hi, 

First of all, so sorry about my very delayed response. Because of legal reasons we still cannot share the wieghts of the model, given that we don't have the permission of all the youtubers. We are currently working on it. 

Also, I would recommend you to use the code you can find in this other[ repo](https://imatge-upc.github.io/wav2pix/)  and add your issues there as this one is no longer maintained :)
